# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('companyname', models.CharField(blank=True, max_length=200, null=True, verbose_name='公司名称')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='市')),
                ('people_num', models.IntegerField(blank=True, null=True, verbose_name='公司人数')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '公司',
                'db_table': 'app_company',
                'verbose_name': '公司',
            },
        ),
    ]
