# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-21 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessage',
            new_name='Message',
        ),
        migrations.AlterField(
            model_name='event',
            name='to',
            field=models.CharField(max_length=100, verbose_name='接收者'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='w_message',
        ),
    ]
