# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-24 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppQuestion',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('question_mode', models.CharField(blank=True, max_length=20, null=True, verbose_name='提问模式')),
                ('question_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='提问价格')),
                ('listen_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='偷听价格')),
                ('listen_num', models.IntegerField(blank=True, null=True)),
                ('like_num', models.IntegerField(blank=True, null=True)),
                ('comment_num', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='提问状态')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_question',
            },
        ),
    ]
