# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-24 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20170224_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appquestion',
            options={'verbose_name': '提问', 'verbose_name_plural': '提问管理'},
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='comment_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='like_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='listen_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='偷听数'),
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='question_mode',
            field=models.CharField(blank=True, choices=[('onetoone', '一对一'), ('free', '免费提问')], max_length=20, null=True, verbose_name='提问模式'),
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to=settings.AUTH_USER_MODEL, verbose_name='回答者'),
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提问者'),
        ),
    ]
