# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20170224_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appquestion',
            name='question_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
