# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20170224_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appquestion',
            name='createtime',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='question_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='appquestion',
            name='updatetime',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
    ]
